### ISSUE TITLE
Cannot build successfully.

### ISSUE THREAD

**Issue by sawyerbutton** [jordanful/Promptspot#5]
Hello, @jordanful,

I've been following the instructions outlined in the Readme in an attempt to create a functioning container. However, I've encountered an error during this process. Here is the full terminal output for your reference:
```bash
Successfully built e74b28ebcf6a
Successfully tagged promptspot_test:latest
Starting promptspot_redis_1 ... done
Creating promptspot_db_1    ... done
Creating promptspot_web_1   ... done
Creating promptspot_test_1  ... done
Attaching to promptspot_redis_1, promptspot_db_1, promptspot_web_1, promptspot_test_1
redis_1  | 1:C 09 Jul 2023 02:29:38.068 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 09 Jul 2023 02:29:38.068 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 09 Jul 2023 02:29:38.068 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     |
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     |
db_1     | Data page checksums are disabled.
web_1    | 2023/07/09 02:29:39 Waiting for: tcp://db:5432
redis_1  | 1:M 09 Jul 2023 02:29:38.069 * monotonic clock: POSIX clock_gettime
db_1     |
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting dynamic shared memory implementation ... posix
test_1   | 2023/07/09 02:29:39 Waiting for: tcp://db:5432
web_1    | 2023/07/09 02:29:39 Problem with dial: dial tcp 172.18.0.3:5432: connect: connection refused. Sleeping 1s
redis_1  | 1:M 09 Jul 2023 02:29:38.070 * Running mode=standalone, port=6379.
redis_1  | 1:M 09 Jul 2023 02:29:38.070 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
db_1     | selecting default max_connections ... 100
test_1   | 2023/07/09 02:29:39 Problem with dial: dial tcp 172.18.0.3:5432: connect: connection refused. Sleeping 1s
redis_1  | 1:M 09 Jul 2023 02:29:38.070 # Server initialized
redis_1  | 1:M 09 Jul 2023 02:29:38.070 # Fatal: Can't initialize Background Jobs.
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting default time zone ... UTC
db_1     | creating configuration files ... ok
db_1     | running bootstrap script ... ok
db_1     | performing post-bootstrap initialization ... sh: locale: not found
db_1     | 2023-07-09 02:29:39.239 UTC [30] WARNING:  no usable system locales were found
promptspot_redis_1 exited with code 1
db_1     | ok
db_1     | syncing data to disk ... ok
db_1     |
db_1     |
db_1     | Success. You can now start the database server using:
db_1     |
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     |
db_1     | initdb: warning: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     | waiting for server to start....2023-07-09 02:29:40.019 UTC [36] LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
db_1     | 2023-07-09 02:29:40.021 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-07-09 02:29:40.028 UTC [37] LOG:  database system was shut down at 2023-07-09 02:29:39 UTC
db_1     | 2023-07-09 02:29:40.032 UTC [36] LOG:  database system is ready to accept connections
db_1     |  done
db_1     | server started
web_1    | 2023/07/09 02:29:40 Problem with dial: dial tcp 172.18.0.3:5432: connect: connection refused. Sleeping 1s
db_1     | CREATE DATABASE
db_1     |
db_1     |
db_1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1     |
db_1     | waiting for server to shut down....2023-07-09 02:29:40.255 UTC [36] LOG:  received fast shutdown request
db_1     | 2023-07-09 02:29:40.257 UTC [36] LOG:  aborting any active transactions
db_1     | 2023-07-09 02:29:40.259 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
db_1     | 2023-07-09 02:29:40.260 UTC [38] LOG:  shutting down
db_1     | 2023-07-09 02:29:40.274 UTC [36] LOG:  database system is shut down
test_1   | 2023/07/09 02:29:40 Problem with dial: dial tcp 172.18.0.3:5432: connect: connection refused. Sleeping 1s
db_1     |  done
db_1     | server stopped
db_1     |
db_1     | PostgreSQL init process complete; ready for start up.
db_1     |
db_1     | 2023-07-09 02:29:40.384 UTC [1] LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
db_1     | 2023-07-09 02:29:40.384 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2023-07-09 02:29:40.384 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2023-07-09 02:29:40.389 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-07-09 02:29:40.395 UTC [51] LOG:  database system was shut down at 2023-07-09 02:29:40 UTC
db_1     | 2023-07-09 02:29:40.399 UTC [1] LOG:  database system is ready to accept connections
web_1    | 2023/07/09 02:29:41 Connected to tcp://db:5432
test_1   | 2023/07/09 02:29:41 Connected to tcp://db:5432
db_1     | 2023-07-09 02:30:06.606 UTC [60] ERROR:  database "promptspot_development" already exists
db_1     | 2023-07-09 02:30:06.606 UTC [60] STATEMENT:  CREATE DATABASE "promptspot_development" ENCODING = 'unicode'
db_1     | 2023-07-09 02:30:06.606 UTC [61] ERROR:  database "promptspot_development" already exists
db_1     | 2023-07-09 02:30:06.606 UTC [61] STATEMENT:  CREATE DATABASE "promptspot_development" ENCODING = 'unicode'
web_1    | Database 'promptspot_development' already exists
test_1   | Database 'promptspot_development' already exists
db_1     | 2023-07-09 02:30:06.730 UTC [65] ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
db_1     | 2023-07-09 02:30:06.730 UTC [65] DETAIL:  Key (extname)=(pgcrypto) already exists.
db_1     | 2023-07-09 02:30:06.730 UTC [65] STATEMENT:  CREATE EXTENSION IF NOT EXISTS "pgcrypto"
test_1   | rails aborted!
test_1   | ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
test_1   | DETAIL:  Key (extname)=(pgcrypto) already exists.
test_1   | /promptspot/db/schema.rb:15:in `block in <main>'
test_1   | /promptspot/db/schema.rb:13:in `<main>'
test_1   |
test_1   | Caused by:
test_1   | PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
test_1   | DETAIL:  Key (extname)=(pgcrypto) already exists.
test_1   | /promptspot/db/schema.rb:15:in `block in <main>'
test_1   | /promptspot/db/schema.rb:13:in `<main>'
test_1   | Tasks: TOP => db:setup => db:schema:load
test_1   | (See full trace by running task with --trace)
promptspot_test_1 exited with code 1
web_1    | ✅ Created model providers and models
web_1    | => Booting Puma
web_1    | => Rails 7.0.5 application starting in development
web_1    | => Run `bin/rails server --help` for more startup options
web_1    |   TRANSACTION (2.2ms)  BEGIN
web_1    |   GoodJob::Process Create (13.1ms)  INSERT INTO "good_job_processes" ("id", "created_at", "updated_at", "state") VALUES ($1, $2, $3, $4) RETURNING "id"  [["id", "ac769277-a3ea-4799-8985-01ff1a12c00e"], ["created_at", "2023-07-09 02:30:15.815134"], ["updated_at", "2023-07-09 02:30:15.815134"], ["state", "{\"id\":\"ac769277-a3ea-4799-8985-01ff1a12c00e\",\"hostname\":\"a977967d4cf9\",\"pid\":1,\"proctitle\":\"bin/rails\",\"preserve_job_records\":true,\"retry_on_unhandled_error\":false,\"schedulers\":[\"GoodJob::Scheduler(queues=* max_threads=5)\"],\"cron_enabled\":false}"]]
web_1    |   GoodJob::Lockable Advisory Lock (3.7ms)  SELECT pg_try_advisory_lock(('x'||substr(md5($1::text), 1, 16))::bit(64)::bigint) AS locked  [["key", "good_job_processes-ac769277-a3ea-4799-8985-01ff1a12c00e"]]
web_1    |   TRANSACTION (3.6ms)  COMMIT
web_1    | Puma starting in single mode...
web_1    | * Puma version: 5.6.5 (ruby 3.0.5-p211) ("Birdie's Version")
web_1    | *  Min threads: 5
web_1    | *  Max threads: 5
web_1    | *  Environment: development
web_1    | *          PID: 1
web_1    | * Listening on http://0.0.0.0:3000
web_1    | Use Ctrl-C to stop
web_1    |   GoodJob::Execution Load (2.2ms)  SELECT "good_jobs".* FROM "good_jobs" WHERE "good_jobs"."id" IN (WITH "rows" AS MATERIALIZED ( SELECT "good_jobs"."id", "good_jobs"."active_job_id" FROM "good_jobs" WHERE "good_jobs"."finished_at" IS NULL AND ("good_jobs"."scheduled_at" <= '2023-07-09 02:30:16.129270' OR "good_jobs"."scheduled_at" IS NULL) ORDER BY priority DESC NULLS LAST, "good_jobs"."created_at" ASC ) SELECT "rows"."id" FROM "rows" WHERE pg_try_advisory_lock(('x' || substr(md5('good_jobs' || '-' || "rows"."active_job_id"::text), 1, 16))::bit(64)::bigint) LIMIT $1) ORDER BY priority DESC NULLS LAST, "good_jobs"."created_at" ASC  [["LIMIT", 1]]
web_1    |   GoodJob::Lockable Unlock Session (0.8ms)  SELECT pg_advisory_unlock_all()::text AS unlocked
web_1    | Started GET "/" for 172.18.0.1 at 2023-07-09 02:30:29 +0000
web_1    | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1    |   ActiveRecord::SchemaMigration Pluck (1.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
web_1    | Processing by TestSuitesController#index as HTML
web_1    | Completed 401 Unauthorized in 71ms (ActiveRecord: 0.0ms | Allocations: 6723)
web_1    |
web_1    |
web_1    | Started GET "/users/sign_in" for 172.18.0.1 at 2023-07-09 02:30:30 +0000
web_1    | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1    | Processing by Devise::SessionsController#new as HTML
web_1    |   Rendering layout layouts/application.html.erb
web_1    |   Rendering devise/sessions/new.html.erb within layouts/application
web_1    |   Rendered devise/shared/_links.html.erb (Duration: 4.2ms | Allocations: 1008)
web_1    |   Rendered devise/sessions/new.html.erb within layouts/application (Duration: 68.1ms | Allocations: 5855)
web_1    |   Rendered /usr/local/bundle/gems/hotwire-livereload-1.2.3/app/views/hotwire/livereload/_head_action_cable.html.erb (Duration: 10.2ms | Allocations: 980)
web_1    |   Rendered layout layouts/application.html.erb (Duration: 4926.1ms | Allocations: 123802)
web_1    | Completed 200 OK in 5030ms (Views: 4986.0ms | ActiveRecord: 3.4ms | Allocations: 146745)
web_1    |
web_1    |
web_1    | Started GET "/cable" for 172.18.0.1 at 2023-07-09 02:30:35 +0000
web_1    | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1    | Started GET "/cable" [WebSocket] for 172.18.0.1 at 2023-07-09 02:30:35 +0000
web_1    | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
web_1    | #<Thread:0x000055d48dcb2390 /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:160 run> terminated with exception (report_on_exception is true):
web_1    | /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:398:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:379:in `establish_connection'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:115:in `block in connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:114:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:325:in `with_socket_timeout'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:174:in `call_loop'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:44:in `subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:14:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:288:in `_subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:20:in `block in subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:19:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:92:in `block in listen'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:95:in `block in with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:94:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:101:in `without_reconnect'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:89:in `listen'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:165:in `block in ensure_listener_running'
web_1    | /usr/local/bundle/gems/redis-4.8.0/lib/redis/connection/ruby.rb:186:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/connection/ruby.rb:186:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/connection/ruby.rb:308:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:385:in `establish_connection'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:115:in `block in connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:114:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:325:in `with_socket_timeout'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:174:in `call_loop'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:44:in `subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:14:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:288:in `_subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:20:in `block in subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:19:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:92:in `block in listen'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:95:in `block in with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:94:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:101:in `without_reconnect'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:89:in `listen'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:165:in `block in ensure_listener_running'
web_1    | Exiting
web_1    |    (0.3ms)  UNLISTEN *
web_1    | [GoodJob] Notifier unsubscribed with UNLISTEN
web_1    |   GoodJob::Lockable Owns Advisory Lock? (1.0ms)  SELECT 1 AS one FROM pg_locks WHERE pg_locks.locktype = 'advisory' AND pg_locks.objsubid = 1 AND pg_locks.classid = ('x' || substr(md5($1::text), 1, 16))::bit(32)::int AND pg_locks.objid = (('x' || substr(md5($2::text), 1, 16))::bit(64) << 32)::bit(32)::int AND pg_locks.pid = pg_backend_pid() LIMIT 1  [["key", "good_job_processes-ac769277-a3ea-4799-8985-01ff1a12c00e"], ["key", "good_job_processes-ac769277-a3ea-4799-8985-01ff1a12c00e"]]
web_1    |   TRANSACTION (0.2ms)  BEGIN
web_1    |   GoodJob::Process Destroy (0.4ms)  DELETE FROM "good_job_processes" WHERE "good_job_processes"."id" = $1  [["id", "ac769277-a3ea-4799-8985-01ff1a12c00e"]]
web_1    |   TRANSACTION (0.3ms)  ROLLBACK
web_1    |   GoodJob::Lockable Advisory Unlock (0.5ms)  SELECT pg_advisory_unlock(('x'||substr(md5($1::text), 1, 16))::bit(64)::bigint) AS unlocked  [["key", "good_job_processes-ac769277-a3ea-4799-8985-01ff1a12c00e"]]
web_1    | /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:398:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:379:in `establish_connection'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:115:in `block in connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:114:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:325:in `with_socket_timeout'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:174:in `call_loop'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:44:in `subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:14:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:288:in `_subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:20:in `block in subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:19:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:92:in `block in listen'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:95:in `block in with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:94:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:101:in `without_reconnect'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:89:in `listen'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:165:in `block in ensure_listener_running'
web_1    | /usr/local/bundle/gems/redis-4.8.0/lib/redis/connection/ruby.rb:186:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/connection/ruby.rb:186:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/connection/ruby.rb:308:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:385:in `establish_connection'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:115:in `block in connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:114:in `connect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:325:in `with_socket_timeout'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:174:in `call_loop'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:44:in `subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/subscribe.rb:14:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:288:in `_subscription'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:20:in `block in subscribe'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/pubsub.rb:19:in `subscribe'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:92:in `block in listen'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:344:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:95:in `block in with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:94:in `with_reconnect'
web_1    | 	from /usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:101:in `without_reconnect'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:89:in `listen'
web_1    | 	from /usr/local/bundle/gems/actioncable-7.0.5/lib/action_cable/subscription_adapter/redis.rb:165:in `block in ensure_listener_running'
promptspot_web_1 exited with code 1
```
It appears that the container was created successfully.

In attempting to diagnose the issue, the error message 
```bash
ERROR: duplicate key value violates unique constraint "pg_extension_name_index" 
```
seems to be the primary concern.

I've tried resolving this issue by removing all related images, containers, and volumes, but the same error persists upon recreating the container.

Could you provide some guidance on how to proceed or any potential solutions to this issue?

Thanks ahead.

**Comment by jordanful** [comment]
Thanks @sawyerbutton. Pull the latest and give it another shot. I believe the issue is that we were creating multiple services in parallel (`web` and `test`) via the Dockerfile and there was a race condition when setting up the databases. I've simplified the services now and I'm having success locally. Thanks again.

**Comment by sawyerbutton** [comment]
> Thanks @sawyerbutton. Pull the latest and give it another shot. I believe the issue is that we were creating multiple services in parallel (`web` and `test`) via the Dockerfile and there was a race condition when setting up the databases. I've simplified the services now and I'm having success locally. Thanks again.

Hi, @jordanful 

I just made another attempt at the Docker build process, and I am pleased to report that it was successful. The site appears to be functioning well on localhost. I truly appreciate your help in this matter - it has been invaluable.

In the coming days, I will explore more features and will keep you updated on my findings. Thank you once again for your assistance.

**Comment by jordanful** [comment]
great @sawyerbutton !
